# Variables that contain the user credentials to access Twitter API
ACCESS_TOKEN = "INSERT TWITTER ACCESS TOKEN HERE"
ACCESS_TOKEN_SECRET = "INSERT TWITTER ACCESS TOKEN SECRET HERE"
CONSUMER_KEY = "INSERT TWITTER CONSUMER KEY HERE"
CONSUMER_SECRET = "INSERT TWITTER CONSUMER SECRET HERE"
#Variables that contains the telegram bot api key
TOFU_CRAWLER_KEY= "INSERT TELEGRAM BOT API KEY HERE"
#Variables that contains the SQL authentication information
MYSQL_HOST="INSERT MYSQL HOST IP HERE.. DEFAULT 127.0.0.1 FOR LOCALHOST"
MYSQL_DBNAME="crawler"
MYSQL_DBUSER="INSERT DB USERNAME HERE"
MYSQL_PASSWD="INSERT DB PASSWORD HERE"
#Variables that contains the Reddit access token information
REDDIT_CLIENT="INSERT REDDIT CLIENT ACCESS TOKEN HERE"
REDDIT_SECRET="INSERT REDDIT ACCESS TOKEN SECRET HERE"
REDDIT_AGENT="INSERT REDDIT AGENT NAME HERE"