'''! @file BotAPI.py
@author Liani Aslam 2609807A
@version 1.0
@brief This file contains the BotAPI class
@section DESCRIPTION
Allows the all the classes to interact with the database
'''

import mysql.connector
import auth_token
import datetime
import pandas as pd


class BotAPI:
    """!BotAPI class
    Defines a telegram bot object to allow TelegramBot class to interact with the database
    to insert and retrieve crawled data from the database

    """
    """!
    @brief Static variables cnx and cursor are used to open and close connections 
    from each time the other classes attempt to make a database connection
    This is to ensure that the database connection is closed after each time 
    the user is done with their commit

    """

    def __init__(self):
        """! BotAPI class initializer
        @brief initalises static variables BotAPI.cnx and BotAPI.cursor
        """
        super().__init__()
        BotAPI.cnx = ""
        BotAPI.cursor = ""

    def openCnx(self):
        """! Open Connections
        @brief openCnx opens a database connection the the local database
        to the user to select, insert or delete data in the database
        @brief cnx contains the database object using python mysql connector
        @brief creates a cursor object to allow the program to execute user comamnds 
        """
        self.cnx = mysql.connector.connect(user=auth_token.MYSQL_DBUSER,
                                           host=auth_token.MYSQL_HOST,
                                           database=auth_token.MYSQL_DBNAME,
                                           password=auth_token.MYSQL_PASSWD)
        self.cursor = self.cnx.cursor()

    def closeCnx(self):
        """! closeCnx(self)  
        @brief closes the database connection after commit is completed
        @brief Ensures that each time user commits to database to release all database 
        resources
        @brief cnx.close() closes the database connection
        @brief cnx.cursor.close() frees up the cursor resource that is currently 
        used by the application
        """
        self.cnx.close()  # closes the database connection
        self.cursor.close()  # closes the database connection

    def selectTweets(self):
        """! Select all tweets that is stored in the database
        @brief Select statement to select all tweets from crawler.testing
        """
        query = ("SELECT * FROM crawler.testing")
        self.cursor.execute(query)
        aList = []
        for i in self.cursor:
            aList.append(i)
        return aList

    def insertTweets(self, author, content, date, likes, retweets, url):
        """! insert tweets
        @brief Inserts tweets from csv file that is generated by TwitterBot.py
        @param author Author of tweet
        @param content Content of tweet
        @param date Date tweeted
        @param likes Number of likes the tweets has
        @param retweets Number of retweets the tweet has
        @param url The URL of the tweet
        @exception self.cnx.commit() failure to commit into database
        """
        try:
            # add_tweets = ("INSERT INTO crawler.tweets " +
            #               "(author, content, date, likes, retweets, url)" +
            #               "VALUES ('"+author+"', '"+content+"', '"+date+"', '"+likes+"', '"+retweets+"', '"+url+"')")
            add_tweets = ("INSERT INTO crawler.testing " +
                          "(author, content, date, likes, retweets, url)" +
                          "VALUES ('"+author+"', '"+content+"', '"+date+"', '"+likes+"', '"+retweets+"', '"+url+"')")
            self.cursor.execute(add_tweets)
            self.cnx.commit()
            print("Insert successful!")
        except:
            print("Fail to insert into database!")

    def readCsv(self):
        """! Inserts generated csv files from crawlers into database
        """
        df = pd.read_csv("tweets.csv", usecols=[
                         'content', 'author', 'date', 'retweets', 'likes', 'url'])
        for index, row in df.iterrows():
            self.insertTweets(str(row['author']), str(row['content']), str(
                row['date']), str(row['likes']), str(row['retweets']), str(row['url']))


